# Final Project Phase 2 Summary
This Jupyter Notebook (.ipynb) will serve as the skeleton file for your submission for Phase 2 of the Final Project. Answer all statements addressed below as specified in the instructions for the project, covering all necessary details. Please be clear and concise in your answers. Each response should be at most 3 sentences. Good luck! <br><br>

Note: To edit a Markdown cell, double-click on its text.

## Jupyter Notebook Quick Tips
Here are some quick formatting tips to get you started with Jupyter Notebooks. This is by no means exhaustive, and there are plenty of articles to highlight other things that can be done. We recommend using HTML syntax for Markdown but there is also Markdown syntax that is more streamlined and might be preferable. 
<a href = "https://towardsdatascience.com/markdown-cells-jupyter-notebook-d3bea8416671">Here's an article</a> that goes into more detail. (Double-click on cell to see syntax)

# Heading 1
## Heading 2
### Heading 3
#### Heading 4
<br>
<b>BoldText</b> or <i>ItalicText</i>
<br> <br>
Math Formulas: $x^2 + y^2 = 1$
<br> <br>
Line Breaks are done using br enclosed in < >.
<br><br>
Hyperlinks are done with: <a> https://www.google.com </a> or 
<a href="http://www.google.com">Google</a><br>

# Data Collection and Cleaning
You are required to provide data collection and cleaning for the three (3) minimum datasets. Create a function for each of the following sections that reads or scrapes data from a file or website, manipulate and cleans the parsed data, and writes the cleaned data into a new file. 

Make sure your data cleaning and manipulation process is not too simple. Performing complex manipulation and using modules not taught in class shows effort, which will increase the chance of receiving full credit.

## Data Sources
Include sources (as links) to your datasets. Add any additional data sources if needed. Clearly indicate if a data source is different from one submitted in your Phase I, as we will check that it satisfies the requirements.
*   Downloaded Dataset Source:
*   Web Collection #1 Source:
*   Web Collection #2 Source:

In [43]:
import numpy as np
import pandas as pd
from pathlib import Path
import requests
from bs4 import BeautifulSoup

## Downloaded Dataset Requirement

Fill in the predefined functions with your data scraping/parsing code. You may modify/rename each function as you seem fit, but you must provide at least 3 separate functions that clean each of your required datasets.

In [ ]:
def downloaded_dataset_parser():
  # Combine separate CSV files into a single DataFrame
  dir_path = Path("../data/raw")
  file_paths = list(dir_path.glob("*.csv"))
  flight_data_separated = [pd.read_csv(file_path)[:-1] for file_path in file_paths]
  flight_data = pd.concat(flight_data_separated, ignore_index=True)

  # Convert format and dtype of date column
  flight_data["Date (MM/DD/YYYY)"] = pd.to_datetime(flight_data["Date (MM/DD/YYYY)"], format="%m/%d/%Y")
  flight_data.rename(columns={"Date (MM/DD/YYYY)": "Date"}, inplace=True)

  # Create departure hour column to merge with weather data
  flight_data["Scheduled departure datetime"] = pd.to_datetime(flight_data["Date"].dt.strftime("%Y-%m-%d") + " " + flight_data["Scheduled departure time"])
  flight_data["Scheduled departure hour"] = flight_data["Scheduled departure datetime"].dt.floor("h")

  # DataFrame to CSV
  flight_data.to_csv("../data/processed/flights.csv", index=False)

  return flight_data



############ Function Call ############
downloaded_dataset_parser()

,Carrier Code,Date,Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Scheduled departure datetime,Scheduled departure hour
0,UA,2025-01-01,213.0,N75432,EWR,08:00,08:00,130.0,127.0,0.0,08:21,21.0,0.0,0.0,0.0,0.0,0.0,2025-01-01 08:00:00,2025-01-01 08:00:00
1,UA,2025-01-01,235.0,N481UA,DEN,16:24,16:38,216.0,208.0,14.0,16:50,12.0,0.0,0.0,0.0,0.0,0.0,2025-01-01 16:24:00,2025-01-01 16:00:00
2,UA,2025-01-01,243.0,N27290,EWR,11:18,11:15,132.0,126.0,-3.0,11:41,26.0,0.0,0.0,0.0,0.0,0.0,2025-01-01 11:18:00,2025-01-01 11:00:00
3,UA,2025-01-01,340.0,N835UA,DEN,08:24,08:24,216.0,233.0,0.0,08:43,19.0,0.0,0.0,17.0,0.0,0.0,2025-01-01 08:24:00,2025-01-01 08:00:00
4,UA,2025-01-01,447.0,N68891,EWR,06:20,06:16,134.0,118.0,-4.0,06:33,17.0,0.0,0.0,0.0,0.0,0.0,2025-01-01 06:20:00,2025-01-01 06:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301124,DL,2025-12-31,3198.0,N948AT,PNS,10:00,09:58,80.0,70.0,-2.0,10:17,19.0,0.0,0.0,0.0,0.0,0.0,2025-12-31 10:00:00,2025-12-31 10:00:00
301125,DL,2025-12-31,8800.0,N936DZ,MSY,11:49,11:40,101.0,89.0,-9.0,11:52,12.0,0.0,0.0,0.0,0.0,0.0,2025-12-31 11:49:00,2025-12-31 11:00:00
301126,DL,2025-12-31,8801.0,N809DN,MIA,12:00,11:55,113.0,143.0,-5.0,12:27,32.0,0.0,0.0,25.0,0.0,0.0,2025-12-31 12:00:00,2025-12-31 12:00:00
301127,DL,2025-12-31,8802.0,N801DZ,MSY,12:25,12:19,101.0,90.0,-6.0,12:41,22.0,0.0,0.0,0.0,0.0,0.0,2025-12-31 12:25:00,2025-12-31 12:00:00
301128,DL,2025-12-31,8806.0,N828DN,BHM,08:00,07:56,57.0,48.0,-4.0,08:09,13.0,0.0,0.0,0.0,0.0,0.0,2025-12-31 08:00:00,2025-12-31 08:00:00

## JSON/API Requirement

In [ ]:
def json_api_parser():
  # API Call Parameters
  lat = 33.6367
  lon = -84.4279
  min_date = "2025-01-01"
  max_date = "2025-12-31"
  url = "https://archive-api.open-meteo.com/v1/archive"

  params = {
    "latitude": lat,
    "longitude": lon,
    "start_date": min_date,
    "end_date": max_date,
    "temperature_unit": "fahrenheit",
    "hourly": ["temperature_2m", "relative_humidity_2m", "dew_point_2m", "apparent_temperature", "precipitation", "rain", "snowfall", "cloud_cover", "windspeed_10m", "windgusts_10m", "winddirection_10m", "weathercode"],
  }

  # API Call
  weather = requests.get(url, params=params).json()

  # JSON to DataFrame
  weather_df = pd.DataFrame(weather["hourly"])
  weather_df["time"] = pd.to_datetime(weather_df["time"])

  # DataFrame to CSV
  weather_df.to_csv("../data/processed/weather.csv", index=False)

  return weather_df





############ Function Call ############
json_api_parser()

,time,temperature_2m,relative_humidity_2m,dew_point_2m,apparent_temperature,precipitation,rain,snowfall,cloud_cover,windspeed_10m,windgusts_10m,winddirection_10m,weathercode
0,2025-01-01 00:00:00,53.1,59,39.3,45.4,0.0,0.0,0.0,0,19.5,44.6,296,0
1,2025-01-01 01:00:00,52.5,56,37.1,44.5,0.0,0.0,0.0,0,19.3,41.4,302,0
2,2025-01-01 02:00:00,50.3,60,36.8,42.1,0.0,0.0,0.0,0,19.4,41.0,303,0
3,2025-01-01 03:00:00,47.8,65,36.8,39.7,0.0,0.0,0.0,0,19.3,41.4,306,0
4,2025-01-01 04:00:00,46.1,69,36.5,38.2,0.0,0.0,0.0,1,18.6,41.0,310,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755,2025-12-31 19:00:00,50.0,18,8.4,40.6,0.0,0.0,0.0,18,12.6,32.4,274,0
8756,2025-12-31 20:00:00,51.0,18,9.3,41.1,0.0,0.0,0.0,1,14.2,34.9,274,0
8757,2025-12-31 21:00:00,50.9,19,10.5,40.9,0.0,0.0,0.0,27,14.6,34.9,265,1
8758,2025-12-31 22:00:00,49.4,21,11.4,39.8,0.0,0.0,0.0,5,13.4,34.2,265,0
8759,2025-12-31 23:00:00,46.0,26,13.1,36.8,0.0,0.0,0.0,27,12.5,27.7,265,1

## HTML Requirement

In [ ]:
def html_parser():
  url = "https://en.wikipedia.org/wiki/Federal_holidays_in_the_United_States"
  agent = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"}
  response = requests.get(url, headers=agent)
  soup = BeautifulSoup(response.content, "html.parser")

  # Extract holiday table
  table = soup.find("table", attrs={"class": "wikitable"})
  holidays = []
  for row in table.find_all("tr")[1:]:
    date = row.find("th").text.strip()
    name = row.find("td").text.strip()
    holidays.append({"Holiday": name, "Date": date})

  # List to DataFrame
  holidays_df = pd.DataFrame(holidays)

  # DataFrame to CSV
  holidays_df.to_csv("../data/processed/holidays.csv", index=False)

  return holidays_df





############ Function Call ############
html_parser()

                                 Holiday                             Date
0                         New Year's Day            January 1(Fixed date)
1    Birthday of Martin Luther King, Jr.      January 15–21(Third Monday)
2                  Washington's Birthday     February 15–21(Third Monday)
3                           Memorial Day           May 25–31(Last Monday)
4   Juneteenth National Independence Day              June 19(Fixed date)
5                       Independence Day               July 4(Fixed date)
6                              Labor Day      September 1–7(First Monday)
7                           Columbus Day      October 8–14(Second Monday)
8                           Veterans Day          November 11(Fixed date)
9                       Thanksgiving Day  November 22–28(Fourth Thursday)
10                         Christmas Day          December 25(Fixed date)

## Additional Dataset Parsing/Cleaning Functions

Write any supplemental (optional) functions here.

In [ ]:
def extra_source1():
    url = "https://en.wikipedia.org/wiki/Hartsfield-Jackson_Atlanta_International_Airport"
    agent = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"}
    response = requests.get(url, headers=agent)
    soup = BeautifulSoup(response.content, "html.parser")

    market_shares = []
    section = soup.find("section", attrs={"aria-labelledby": "Airline_market_share"})
    table = section.find("table")
    for row in table.find_all("tr")[1:]:
        entries = [cell.text.strip() for cell in row.find_all("td")]
        market_shares.append(entries)

    # List to DataFrame
    market_shares_df = pd.DataFrame(market_shares, columns=["Rank", "Airline", "Passengers", "Share"])
    
    # DataFrame to CSV
    market_shares_df.to_csv("../data/processed/market_shares.csv", index=False)

    return market_shares_df

    
############ Function Call ############
extra_source1()

   Rank                                      Airline  Passengers   Share
0     1  Delta Air Lines (includes Delta Connection)  84,851,005  80.16%
1     2                            Frontier Airlines   7,053,413   6.66%
2     3                           Southwest Airlines   3,944,112   3.73%
3     4  American Airlines (includes American Eagle)   2,653,658   2.51%
4     5                              United Airlines   1,937,230   1.83%
5     6                              Spirit Airlines   1,126,697   1.06%
6     7                                      JetBlue     670,622   0.63%
7     8                              Alaska Airlines     406,935   0.38%
8     9                                   Air France     369,789   0.35%
9    10                              Virgin Atlantic     334,177   0.32%
10                                             Other   2,506,610   2.37%

In [48]:
# Define further extra source functions as necessary

# Inconsistencies

For each inconsistency (NaN, null, duplicate values, empty strings, etc.) you discover in your datasets, write at least 2 sentences stating the significance, how you identified it, and how you handled it.

1. 

2. 

3. 

4. (if applicable)

5. (if applicable)